'use strict';
(() => {
 const D=window.ENCYCLOPEDIA, root=document.getElementById('contenido'), nav=document.getElementById('navigation');
 const fileMode=location.protocol==='file:', byId=new Map(D.entries.map(e=>[e.id,e]));
 const labels={campeones:'Campeones',objetos:'Objetos',runas:'Runas',matchups:'Matchups',otros:'Otros'};
 const icons={search:'<circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 4.5 4.5"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',back:'<path d="M19 12H5m6-6-6 6 6 6"/>',external:'<path d="M14 4h6v6M10 14 20 4M20 14v6H4V4h6"/>',book:'<path d="M3 5c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2zM12 7v15"/>'};
 const svg=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.book}</svg>`;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
 const slug=s=>normalize(s).replace(/ /g,'-');
 const href=route=>fileMode?'#'+route:route;
 const link=(route,label,cls='')=>`<a class="${cls}" data-route href="${esc(href(route))}">${label}</a>`;
 const paragraphText=pids=>pids.map(i=>D.paragraphs[i].text).join(' ');
 const searchable=D.search.map(s=>({...s,nTitle:normalize(s.title),nMeta:normalize(s.title+' '+s.group+' '+s.category),nBody:normalize(paragraphText(s.pids))}));
 const entrySearch=new Map(searchable.filter(x=>byId.has(x.route)).map(x=>[x.route,x]));
 const terms=new Map();for(const e of D.entries)if(['campeones','objetos','runas'].includes(e.category)&&e.title.length>3&&!terms.has(e.title))terms.set(e.title,e.id);
 const termPattern=new RegExp('(?<![\\p{L}\\p{N}])('+[...terms.keys()].sort((a,b)=>b.length-a.length).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')(?![\\p{L}\\p{N}])','gu');
 let routeState,visibleCount=36,searchTimer,activeSuggestion=-1,currentSuggestions=[];
 function readRoute(){const raw=fileMode?(location.hash.slice(1)||'/'):location.pathname+location.search+location.hash;const [pathAndQuery,anchor='']=raw.split('#');const url=new URL(pathAndQuery,'https://enciclopedia.local');return {path:decodeURI(url.pathname).replace(/\/$/,'')||'/',params:url.searchParams,anchor:decodeURIComponent(anchor)};}
 function go(route){if(fileMode){if(location.hash==='#'+route)render();else location.hash=route;}else{history.pushState({},'',route);render();}}
 function image(src,alt,cls='',eager=false){return src?`<img src="${esc(src)}?v=${D.source.sha256.slice(0,8)}" alt="${esc(alt)}" class="${cls}" loading="${eager?'eager':'lazy'}" decoding="async"${eager?' fetchpriority="high"':''}>`:`<span class="icon-fallback">${svg('book')}</span>`;}
 function rich(text,current='',autolink=true){if(!autolink)return esc(text);let out='',last=0;termPattern.lastIndex=0;for(const m of text.matchAll(termPattern)){out+=esc(text.slice(last,m.index));const id=terms.get(m[0]);out+=id!==current?link(id,esc(m[0]),'inline-link'):esc(m[0]);last=m.index+m[0].length;}return out+esc(text.slice(last));}
 function prose(pids,current='',autolink=true){let html='',inList=false;for(const id of pids){const p=D.paragraphs[id];if(!p||!p.text)continue;if(p.bullet){if(!inList){html+='<ul>';inList=true;}html+='<li>'+rich(p.text,current,autolink)+'</li>';continue;}if(inList){html+='</ul>';inList=false;}if(p.links?.length){html+='<p class="source-line">'+p.links.map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(l.text.trim())}${svg('external')}</a>`).join(' · ')+'</p>';continue;}if(p.style.startsWith('HEADING')||p.style==='TITLE'){const level=p.style==='HEADING_3'?3:2;html+=`<h${level}>${esc(p.text)}</h${level}>`;continue;}const note=/^(Evidencia:|Cifras pendientes|Disponibilidad:|La cobertura avanzada|Pendientes que afectan)/.test(p.text);html+=`<p${note?' class="evidence-note"':''}>${rich(p.text,current,autolink)}</p>`;}if(inList)html+='</ul>';return '<div class="prose">'+html+'</div>';}
 function breadcrumbs(parts){return `<nav class="breadcrumbs" aria-label="Ruta de navegación">${link('/','Inicio')}${parts.map((p,i)=>`<span class="sep" aria-hidden="true">/</span>${p.route?link(p.route,esc(p.label)):`<span aria-current="page">${esc(p.label)}</span>`}`).join('')}</nav>`;}
 function footer(){return `<footer class="footer"><span>Hecho por CatFaceCorp. ©</span><div>${link('/documento','Leer la enciclopedia completa')}<a href="${D.source.url}" target="_blank" rel="noopener noreferrer">Documento original ${svg('external')}</a></div></footer>`;}
 function searchBar(value='',home=false){return `<div class="${home?'':'page-search'}"><div class="search-frame"><form class="search-form" role="search" data-search-form>${svg('search','search-symbol')}<label class="sr-only" for="encyclopedia-search">Buscar en la enciclopedia</label><input id="encyclopedia-search" type="search" autocomplete="off" spellcheck="false" value="${esc(value)}" placeholder="Buscar campeón, objeto, runa, matchup o mecánica..." aria-controls="suggestions" aria-expanded="false" role="combobox" aria-autocomplete="list"><button class="circle-button" aria-label="Buscar" type="submit">${svg('arrow')}</button></form><div id="suggestions" class="suggestions" role="listbox" aria-label="Sugerencias de búsqueda" hidden></div></div></div>`;}
 function findResults(q){q=normalize(q);if(!q)return [];const words=q.split(' ');return searchable.map(s=>{let score=s.nTitle===q?0:s.nTitle.startsWith(q)?1:s.nTitle.includes(q)?2:words.every(w=>s.nMeta.includes(w))?3:words.every(w=>(s.nMeta+' '+s.nBody).includes(w))?5:99;return {s,score};}).filter(x=>x.score<99).sort((a,b)=>a.score-b.score||(byId.has(a.s.route)?0:1)-(byId.has(b.s.route)?0:1)||a.s.title.localeCompare(b.s.title,'es')).map(x=>x.s);}
 function snippet(pids,q=''){const paras=pids.map(i=>D.paragraphs[i]).filter(p=>p.text&&!p.links?.length&&!p.style.startsWith('HEADING'));let t=(paras.find(p=>normalize(p.text).includes(normalize(q)))||paras[0])?.text||'';return t.length>230?t.slice(0,227)+'…':t;}
 function card(e){if(e.category==='campeones')return link(e.id,`<div class="card-image">${image(e.image,'Ilustración oficial de '+e.title)}<span class="card-arrow">${svg('arrow')}</span></div><div class="card-body"><h2>${esc(e.title)}</h2><span class="card-meta">Pasiva · Q · W · E · R</span></div>`,'entity-card');if(e.category==='objetos'||e.category==='runas'||e.image)return link(e.id,`${image(e.image,'Icono de '+e.title,'asset-icon '+(e.category==='runas'?'rune-icon':''))}<div class="card-body"><h2>${esc(e.title)}</h2><span class="card-meta">${esc(e.group)}</span></div>`,'entity-card compact-card');return link(e.id,`<div class="card-body"><span class="card-meta">${esc(e.group)}</span><h2>${esc(e.title)}</h2><p class="card-excerpt">${esc(snippet(e.pids))}</p></div><span class="read-more">Leer entrada ${svg('arrow')}</span>`,'entity-card editorial-card');}
 function home(){document.title='League of Legends — CatFaceCorp.';return `<section class="home">${image('assets/champions/Zoe.webp','Ilustración oficial de Zoe de League of Legends','home-art',true)}<div class="hero-content"><h1>League of Legends</h1><p class="hero-credit">Hecho por CatFaceCorp. ©</p>${searchBar('',true)}<p class="hero-hint">Explora el juego. Empieza por ${link('/campeones/ahri','Ahri')}, ${link('/campeones/zoe','Zoe')} o una mecánica.</p></div><div class="home-bottom"><p>Grieta del Invocador<br>Una enciclopedia para conocer el juego.</p>${link('/documento','Dentro de la enciclopedia '+svg('arrow'),'text-link')}</div></section>`;}
 const descriptions={campeones:'Cada campeón, en detalle. Explora su kit, sus cifras y las respuestas prácticas que recoge la enciclopedia.',objetos:'Efectos, componentes y cifras del catálogo documentado. Consulta las notas de disponibilidad de cada entrada.',runas:'Explora las ramas y encuentra los efectos y valores presentes en la enciclopedia.',matchups:'Enfrentamientos en botlane y guías para responder a los apoyos. Solo las entradas que contiene el documento.',otros:'Las reglas detrás de la partida. Movimiento, control de masas, objetivos, hechizos, sistemas e interacciones.'};
 function chapterIntro(category,group){const ids={campeones:['07'],objetos:['08'],runas:['09'],matchups:['11','12'],otros:[]}[category];const paragraphs=[];for(const id of ids){const chapter=D.chapters.find(c=>c.id===id);for(const pid of chapter.pids.slice(1)){const p=D.paragraphs[pid];if(p.style==='HEADING_2')break;if(p.text&&!p.links.length)paragraphs.push(p.text);}}return paragraphs.length?`<details class="chapter-intro"><summary>Alcance y notas del documento</summary>${paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</details>`:'';}
 function categoryPage(category){document.title=labels[category]+' — Enciclopedia de League of Legends';const all=D.entries.filter(e=>e.category===category);const groups=[...new Set(all.map(e=>e.group))];const selected=routeState.params.get('grupo')||'';const q=routeState.params.get('q')||'';return `<div class="container"><header class="page-top">${breadcrumbs([{label:labels[category]}])}<span class="eyebrow">La enciclopedia</span><h1>${labels[category]}</h1><p class="page-lede">${descriptions[category]}</p></header>${category==='otros'&&!selected?`<div class="group-grid">${groups.map(g=>link('/otros?grupo='+encodeURIComponent(g),`<div><h2>${esc(g)}</h2><small>${all.filter(e=>e.group===g).length} entradas</small></div>${svg('arrow')}`,'group-card')).join('')}</div><div class="section-row"><h2>Todas las entradas</h2></div>`:''}${selected?`<div class="section-row"><h2>${esc(selected)}</h2>${link('/'+category,'Ver todas','back-link')}</div>`:''}${chapterIntro(category,selected)}<div class="toolbar"><label class="filter-input">${svg('search')}<span class="sr-only">Filtrar ${labels[category].toLowerCase()}</span><input id="catalog-search" type="search" placeholder="Buscar en ${labels[category].toLowerCase()}…" value="${esc(q)}"></label><div class="filter-right">${groups.length>1?`<label class="sr-only" for="group-filter">Filtrar por grupo</label><select id="group-filter"><option value="">Todos los grupos</option>${groups.map(g=>`<option${g===selected?' selected':''}>${esc(g)}</option>`).join('')}</select>`:''}<span id="catalog-count" aria-live="polite"></span></div></div><div id="catalog-grid" class="grid ${category==='campeones'?'champion-grid':''}"></div><button id="catalog-more" class="load-more" type="button">Mostrar más</button></div>${footer()}`;}
 function updateCatalog(reset=false){if(reset)visibleCount=36;const category=routeState.path.slice(1),query=normalize(document.getElementById('catalog-search').value),group=document.getElementById('group-filter')?.value||'';const words=query.split(' ').filter(Boolean);const all=D.entries.filter(e=>e.category===category&&(!group||e.group===group)&&words.every(w=>{const s=entrySearch.get(e.id);return (s.nMeta+' '+s.nBody).includes(w);}));document.getElementById('catalog-count').textContent=all.length+' '+(all.length===1?'entrada':'entradas');document.getElementById('catalog-grid').innerHTML=all.length?all.slice(0,visibleCount).map(card).join(''):'<div class="empty"><h2>No hay coincidencias</h2><p>Prueba con otro nombre o cambia el filtro.</p></div>';document.getElementById('catalog-more').hidden=visibleCount>=all.length;}
 function related(e){const entries=[...new Set(e.related)].map(id=>byId.get(id)).filter(Boolean);return entries.length?`<section class="related" id="relacionado"><h2>Contenido relacionado</h2><p class="notice">Entradas que mencionan este campeón o que están citadas en esta ficha.</p><div class="grid">${entries.map(card).join('')}</div></section>`:'';}
 function champion(e){document.title=e.title+' — Enciclopedia de League of Legends';const ps=e.pids.map(i=>D.paragraphs[i]),sections=[],intro=[];let section=null;for(const p of ps){if(p.style==='HEADING_3'){section={title:p.text,pids:[],anchor:slug(p.text),ability:e.abilities.find(a=>a.pid===p.pid)};if(section.ability)section.anchor=section.ability.anchor;sections.push(section);}else if(section)section.pids.push(p.pid);else intro.push(p.pid);}return `<header class="detail-hero">${image(e.image,'Splash art oficial de '+e.title,'',true)}<div class="container">${breadcrumbs([{label:'Campeones',route:'/campeones'},{label:e.title}])}<div><span class="eyebrow">Campeones de la Grieta</span><h1>${esc(e.title)}</h1><p>Habilidades, mecánicas y cómo responder a su kit.</p></div></div></header><div class="container detail-layout"><aside class="toc" aria-label="Contenido de la ficha"><strong>En esta ficha</strong><a href="${esc(href(e.id+'#datos'))}" data-route>Datos del campeón</a>${sections.map(s=>link(e.id+'#'+s.anchor,esc(s.ability?((s.ability.slot==='P'?'Pasiva':s.ability.slot)+' · '+s.ability.title):s.title))).join('')}${e.related.length?link(e.id+'#relacionado','Contenido relacionado'):''}${link('/campeones','← Todos los campeones')}</aside><article class="article"><div class="ability-jump" aria-label="Ir a una habilidad">${e.abilities.map(a=>link(e.id+'#'+a.anchor,image(a.image,'')+esc(a.slot==='P'?'Pasiva':a.slot))).join('')}</div><section class="article-intro article-section" id="datos"><h2>Datos del campeón</h2>${prose(intro,e.id)}</section>${sections.map(s=>`<section class="article-section ${s.ability?'ability-card':''}" id="${s.anchor}">${s.ability?`<div class="ability-heading">${image(s.ability.image,'Icono de '+s.ability.title)}<div><span class="slot">${s.ability.slot==='P'?'Pasiva':'Habilidad '+s.ability.slot}</span><h2>${esc(s.ability.title)}</h2></div></div>`:`<h2>${esc(s.title)}</h2>`}${prose(s.pids,e.id)}</section>`).join('')}${related(e)}</article></div>${footer()}`;}
 function detail(e){document.title=e.title+' — Enciclopedia de League of Legends';return `<div class="container"><header class="detail-top">${breadcrumbs([{label:labels[e.category],route:'/'+e.category},{label:e.title}])}<div class="entity-title-row">${e.image?image(e.image,'Icono de '+e.title,'asset-icon '+(e.category==='runas'?'rune-icon':''),true):''}<div><span class="eyebrow">${esc(e.group)}</span><h1>${esc(e.title)}</h1></div></div></header><article class="simple-article">${prose(e.pids,e.id)}${related(e)}${link('/'+e.category,svg('back')+' Volver a '+labels[e.category].toLowerCase(),'back-link')}</article></div>${footer()}`;}
 function searchPage(){const q=routeState.params.get('q')||'';document.title='Buscar '+q+' — Enciclopedia de League of Legends';return `<div class="container"><header class="page-top">${breadcrumbs([{label:'Buscar'}])}<span class="eyebrow">Toda la enciclopedia</span><h1>Encuentra una respuesta.</h1></header>${searchBar(q)}<p id="search-count" class="search-count" aria-live="polite"></p><div id="search-results" class="search-results"></div><button id="search-more" class="load-more" type="button">Mostrar más resultados</button></div>${footer()}`;}
 function updateResults(){const q=routeState.params.get('q')||'',results=findResults(q);document.getElementById('search-count').textContent=q?results.length+' resultados para «'+q+'»':'Escribe un nombre, una habilidad o una mecánica.';document.getElementById('search-results').innerHTML=results.length?results.slice(0,visibleCount).map(s=>link(s.route,`${image(s.image,'')}<div class="result-main"><span class="result-meta">${esc(s.category)}${s.group!==s.category?' · '+esc(s.group):''}</span><h2>${esc(s.title)}</h2><p class="result-snippet">${esc(snippet(s.pids,q))}</p></div>${svg('arrow')}`,'result-card')).join(''):q?'<div class="empty"><h2>No encontramos esa entrada</h2><p>Prueba un nombre parcial o un término distinto. La búsqueda utiliza únicamente el contenido de la enciclopedia.</p></div>':'';document.getElementById('search-more').hidden=visibleCount>=results.length;}
 function documentPage(){const id=routeState.params.get('capitulo')||'01',ch=D.chapters.find(c=>c.id===id);document.title='Documento completo — Enciclopedia de League of Legends';return `<div class="container"><header class="page-top">${breadcrumbs([{label:'Documento completo'}])}<span class="eyebrow">La fuente de esta web</span><h1>La enciclopedia completa.</h1><p class="page-lede">El contenido del documento, organizado por capítulos. Se conservan sus cifras, fuentes y notas de verificación.</p><div class="doc-source"><a href="${D.source.url}" target="_blank" rel="noopener noreferrer">Abrir el documento original</a></div></header><div class="doc-layout"><aside class="toc" aria-label="Capítulos del documento"><strong>Índice</strong>${link('/documento?capitulo=portada','Portada e índice original')}${D.chapters.map(c=>link('/documento?capitulo='+c.id,c.id+' · '+esc(c.title))).join('')}</aside><article class="doc-body"><div class="doc-title"><h2>${esc(ch?.title||'Portada e índice original')}</h2></div>${prose(ch?ch.pids.slice(1):D.front,'',false)}</article></div></div>${footer()}`;}
 function render(){routeState=readRoute();visibleCount=36;const category=routeState.path.split('/')[1];document.body.dataset.page=routeState.path==='/'?'home':'inner';nav.innerHTML='<nav aria-label="Categorías principales">'+Object.keys(labels).map(k=>`<a class="nav-link" data-route href="${href('/'+k)}"${category===k?' aria-current="page"':''}>${labels[k].toLocaleUpperCase('es')}</a>`).join('')+'</nav>';const e=byId.get(routeState.path);if(routeState.path==='/')root.innerHTML=home();else if(e)root.innerHTML=e.category==='campeones'?champion(e):detail(e);else if(Object.keys(labels).some(k=>routeState.path==='/'+k))root.innerHTML=categoryPage(category);else if(routeState.path==='/buscar')root.innerHTML=searchPage();else if(routeState.path==='/documento')root.innerHTML=documentPage();else{document.title='Página no encontrada — Enciclopedia';root.innerHTML=`<div class="container not-found"><h1>Esta página no existe.</h1><p>Vuelve a explorar la enciclopedia.</p>${link('/','Ir al inicio')}</div>`;}bindPage();if(routeState.anchor)requestAnimationFrame(()=>document.getElementById(routeState.anchor)?.scrollIntoView({behavior:'instant',block:'start'}));else window.scrollTo({top:0,behavior:'instant'});document.getElementById('announcer').textContent=document.title;}
 function bindPage(){if(document.getElementById('catalog-grid')){updateCatalog();document.getElementById('catalog-search').addEventListener('input',()=>updateCatalog(true));document.getElementById('group-filter')?.addEventListener('change',()=>updateCatalog(true));document.getElementById('catalog-more').onclick=()=>{visibleCount+=36;updateCatalog();};}if(document.getElementById('search-results')){updateResults();document.getElementById('search-more').onclick=()=>{visibleCount+=36;updateResults();};}const form=root.querySelector('[data-search-form]'),input=document.getElementById('encyclopedia-search');if(form){form.onsubmit=ev=>{ev.preventDefault();const q=input.value.trim();if(q)go('/buscar?q='+encodeURIComponent(q));};input.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>suggest(input),120);};input.onkeydown=ev=>{if(ev.key==='Escape'){closeSuggestions();return;}if(ev.key==='ArrowDown'||ev.key==='ArrowUp'){ev.preventDefault();if(!currentSuggestions.length)suggest(input);activeSuggestion=Math.max(0,Math.min(currentSuggestions.length-1,activeSuggestion+(ev.key==='ArrowDown'?1:-1)));paintActive(input);}else if(ev.key==='Enter'&&activeSuggestion>=0&&currentSuggestions[activeSuggestion]){ev.preventDefault();go(currentSuggestions[activeSuggestion].route);}};}}
 function suggest(input){const q=input.value.trim(),box=document.getElementById('suggestions');if(!box)return;activeSuggestion=-1;currentSuggestions=q?findResults(q).slice(0,6):[];box.hidden=!q;input.setAttribute('aria-expanded',String(!!q));input.removeAttribute('aria-activedescendant');box.innerHTML=currentSuggestions.length?currentSuggestions.map((s,i)=>`<a id="suggestion-${i}" class="suggestion" data-route role="option" aria-selected="false" href="${esc(href(s.route))}">${image(s.image,'')}<span><strong>${esc(s.title)}</strong><small>${esc(s.category)} · ${esc(s.group)}</small></span>${svg('arrow')}</a>`).join('')+link('/buscar?q='+encodeURIComponent(q),'Ver todos los resultados '+svg('arrow'),'suggestion-more'):'<p class="suggestion">No hay coincidencias. Prueba otro término.</p>';}
 function paintActive(input){root.querySelectorAll('.suggestion[role=option]').forEach((a,i)=>{a.classList.toggle('active',i===activeSuggestion);a.setAttribute('aria-selected',String(i===activeSuggestion));});if(activeSuggestion>=0)input.setAttribute('aria-activedescendant','suggestion-'+activeSuggestion);}
 function closeSuggestions(){const box=document.getElementById('suggestions');if(box)box.hidden=true;document.getElementById('encyclopedia-search')?.setAttribute('aria-expanded','false');activeSuggestion=-1;currentSuggestions=[];}
 document.addEventListener('click',ev=>{const a=ev.target.closest('a[data-route]');if(a&&!ev.ctrlKey&&!ev.metaKey&&!ev.shiftKey&&ev.button===0){ev.preventDefault();const raw=a.getAttribute('href'),target=fileMode?raw.slice(1):raw;const [path,anchor]=target.split('#');const here=routeState.path+(location.search||'');if(path===here&&anchor){if(fileMode)location.hash=target;else history.pushState({},'',target);document.getElementById(decodeURIComponent(anchor))?.scrollIntoView();}else go(target);return;}if(!ev.target.closest('.search-frame'))closeSuggestions();});
 document.addEventListener('keydown',ev=>{if(ev.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){const input=document.getElementById('encyclopedia-search')||document.getElementById('catalog-search');if(input){ev.preventDefault();input.focus();}}});
 document.addEventListener('error',ev=>{if(ev.target.tagName==='IMG'){ev.target.classList.add('no-image');ev.target.alt=ev.target.alt||'Imagen no disponible';}},true);
 window.addEventListener('popstate',render);if(fileMode)window.addEventListener('hashchange',render);
 render();
})();
